name: Release Seats

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes (best possible)
  workflow_dispatch:

jobs:
  release-seats:
    runs-on: ubuntu-latest
    steps:
      - name: Release Seats
        run: |
          curl -X GET "https://theater-booking-system.onrender.com/cron/release-seats" \
          -H "Authorization: Bearer ${{ secrets.CRON_API_KEY }}"
