name: Run Movie Cron Jobs

on:
  schedule:
    - cron: "30 6 * * *" # Runs at 12:00 AM IST (6:30 AM UTC)
    - cron: "40 6 * * *" # Runs at 12:10 AM IST (6:40 AM UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-cron-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Movies
        run: |
          curl -X GET "https://theater-booking-system.onrender.com/cron/sync" \
          -H "Authorization: Bearer ${{ secrets.CRON_API_KEY }}"

      - name: Delete Old Movies
        run: |
          curl -X GET "https://theater-booking-system.onrender.com/cron/delete-movies" \
          -H "Authorization: Bearer ${{ secrets.CRON_API_KEY }}"
